### ISSUE TITLE
What's remaining for v1?

### ISSUE THREAD

**Issue by benjaminoakes** [vincetse/herokuish-action#2]
[I love this idea](https://www.benjaminoakes.com/programming/2021/05/13/Buildpack-CI-on-GitHub-Actions/). Thanks for putting it together!

I [noticed](https://github.com/marketplace/actions/buildpack-ci) that the current version (v1-beta1) is a pre-release. What's left to make it v1?

**Comment by vincetse** [comment]
Honestly, it's feature-complete in my eyes, and I left it as a pre-release to let it soak.  I think it's ready for v1.  Have you used it? Any feedback?

**Comment by vincetse** [comment]
Published v1.
